# Dependabot configuration - keep dependencies updated
# Note: For a single-maintainer local tool, you can also just run
# 'dotnet list package --outdated' manually instead of using this.

version: 2
updates:
  # NuGet package updates - monthly is fine for a local tool
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      all-dependencies:
        patterns:
          - "*"  # Group all updates into single PRs

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3