using NUnit.Framework;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading.Tasks;

namespace prepareBikeParking.Tests;

public class AddRefGbfsOscTests
{
    private const string TempSystem = "TestSystem_AddRefGbfs";
    private const string OscFile = "bikeshare_add_ref_gbfs.osc";
    private const string MismatchFile = "bikeshare_refgbfs_mismatches.geojson";
    private const string SystemId = "test_sys";

    [SetUp]
    public void CleanStart()
    {
        var full = prepareBikeParking.FileManager.GetSystemFullPath(TempSystem, "");
        if (Directory.Exists(full)) Directory.Delete(full, true);
    }

    private static GeoPoint OsmNode(long id, int version, string refValue, string? refGbfs = null, bool isDisused = false, string name = "Station")
    {
        var tagsJson = new System.Text.StringBuilder();
        tagsJson.Append("{");
        tagsJson.Append($"\"name\":\"{name}\",\"ref\":\"{refValue}\"");
        if (refGbfs != null) tagsJson.Append($",\"ref:gbfs\":\"{refGbfs}\"");
        if (isDisused) tagsJson.Append(",\"disused:amenity\":\"bicycle_rental\"");
        else tagsJson.Append(",\"bicycle_rental\":\"docking_station\"");
        tagsJson.Append("}");

        var json = $"{{\"type\":\"node\",\"id\":{id},\"version\":{version},\"lat\":43.65,\"lon\":-79.4,\"tags\":{tagsJson}}}";
        var element = JsonDocument.Parse(json).RootElement.Clone();

        return new GeoPoint
        {
            id = refValue,
            name = name,
            lat = "43.65",
            lon = "-79.4",
            capacity = 0,
            IsDisused = isDisused,
            RefGbfs = refGbfs,
            osmId = id.ToString(),
            osmType = "node",
            osmVersion = version,
            osmXmlElement = element,
        };
    }

    private static GeoPoint GbfsPoint(string id) =>
        new GeoPoint { id = id, name = "GBFS " + id, lat = "43.65", lon = "-79.4", capacity = 0 };

    [Test]
    public async Task TagsMatching_Ref_WithoutRefGbfs()
    {
        var osm = new List<GeoPoint> { OsmNode(100, 3, "7000") };
        var gbfs = new List<GeoPoint> { GbfsPoint("7000") };

        await OsmFileFunctions.GenerateAddRefGbfsOsmChangeFile(osm, gbfs, TempSystem, SystemId);

        var osc = await prepareBikeParking.FileManager.ReadSystemTextFileAsync(TempSystem, OscFile);
        Assert.That(osc, Does.Contain("<node id=\"100\" version=\"3\""));
        Assert.That(osc, Does.Contain("<tag k=\"ref:gbfs\" v=\"test_sys:7000\"/>"));
        Assert.That(osc, Does.Contain("<tag k=\"name\" v=\"Station\"/>"));
        Assert.That(osc, Does.Contain("<tag k=\"ref\" v=\"7000\"/>"));
    }

    [Test]
    public async Task SkipsOsm_WithExistingMatchingRefGbfs()
    {
        var osm = new List<GeoPoint> { OsmNode(101, 1, "7001", refGbfs: "test_sys:7001") };
        var gbfs = new List<GeoPoint> { GbfsPoint("7001") };

        await OsmFileFunctions.GenerateAddRefGbfsOsmChangeFile(osm, gbfs, TempSystem, SystemId);

        var oscPath = prepareBikeParking.FileManager.GetSystemFullPath(TempSystem, OscFile);
        Assert.That(File.Exists(oscPath), Is.False, "No OSC should be written when nothing to add");
    }

    [Test]
    public async Task SkipsOsm_WithNoMatchingGbfsId()
    {
        var osm = new List<GeoPoint> { OsmNode(102, 1, "ORPHAN") };
        var gbfs = new List<GeoPoint> { GbfsPoint("7000") };

        await OsmFileFunctions.GenerateAddRefGbfsOsmChangeFile(osm, gbfs, TempSystem, SystemId);

        var oscPath = prepareBikeParking.FileManager.GetSystemFullPath(TempSystem, OscFile);
        Assert.That(File.Exists(oscPath), Is.False);
    }

    [Test]
    public async Task SkipsOsm_WithAutoGeneratedId()
    {
        var osm = new List<GeoPoint> {
            new GeoPoint { id = "osm_999", name = "NoRef", lat = "43.65", lon = "-79.4", osmId = "999", osmType = "node", osmVersion = 1 }
        };
        var gbfs = new List<GeoPoint> { GbfsPoint("7000") };

        await OsmFileFunctions.GenerateAddRefGbfsOsmChangeFile(osm, gbfs, TempSystem, SystemId);

        var oscPath = prepareBikeParking.FileManager.GetSystemFullPath(TempSystem, OscFile);
        Assert.That(File.Exists(oscPath), Is.False);
    }

    [Test]
    public async Task MismatchedRefGbfs_GoesToMismatchReport_NotOsc()
    {
        var osm = new List<GeoPoint> { OsmNode(103, 1, "7002", refGbfs: "wrong_sys:7002") };
        var gbfs = new List<GeoPoint> { GbfsPoint("7002") };

        await OsmFileFunctions.GenerateAddRefGbfsOsmChangeFile(osm, gbfs, TempSystem, SystemId);

        var oscPath = prepareBikeParking.FileManager.GetSystemFullPath(TempSystem, OscFile);
        Assert.That(File.Exists(oscPath), Is.False, "Mismatched stations should not be auto-tagged");

        var mismatch = await prepareBikeParking.FileManager.ReadSystemTextFileAsync(TempSystem, MismatchFile);
        Assert.That(mismatch, Does.Contain("wrong_sys:7002"));
        Assert.That(mismatch, Does.Contain("test_sys:7002"));
    }

    [Test]
    public async Task DisusedStation_WithMatchingRef_StillTagged()
    {
        var osm = new List<GeoPoint> { OsmNode(104, 2, "7003", isDisused: true) };
        var gbfs = new List<GeoPoint> { GbfsPoint("7003") };

        await OsmFileFunctions.GenerateAddRefGbfsOsmChangeFile(osm, gbfs, TempSystem, SystemId);

        var osc = await prepareBikeParking.FileManager.ReadSystemTextFileAsync(TempSystem, OscFile);
        Assert.That(osc, Does.Contain("<tag k=\"ref:gbfs\" v=\"test_sys:7003\"/>"));
        Assert.That(osc, Does.Contain("<tag k=\"disused:amenity\" v=\"bicycle_rental\"/>"));
    }

    [Test]
    public async Task NoModifications_NoOscFile()
    {
        var osm = new List<GeoPoint>();
        var gbfs = new List<GeoPoint> { GbfsPoint("7000") };

        await OsmFileFunctions.GenerateAddRefGbfsOsmChangeFile(osm, gbfs, TempSystem, SystemId);

        var oscPath = prepareBikeParking.FileManager.GetSystemFullPath(TempSystem, OscFile);
        Assert.That(File.Exists(oscPath), Is.False);
    }
}
